Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -25,16 +25,27 @@ phases:
   build:
     commands:
       - echo Starting dry run for migration from Wasabi to S3...
-      - rclone copy --dry-run --files-from copylist.txt wasabi:duplitech-samsung/poc/ s3:wasabi-to-s3-automated-data-transfer-logs/wasabi-files/  -vv
+      - |
+        if rclone copy --dry-run --files-from copylist.txt wasabi:duplitech-samsung/poc/ s3:wasabi-to-s3-automated-data-transfer-logs/wasabi-files/ --progress -vv; then
+          echo "Dry run completed successfully."
+        else
+          echo "Dry run failed." >&2
+          exit 1
+        fi
       - echo "Dry run successful. Proceeding with actual migration..."
-      - echo Generating timestamp and log file name...
+        
       - TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
       - LOG_FILE="transfer-log-${TIMESTAMP}.txt"
-      - echo Starting actual migration from Wasabi to S3...
-      - rclone copy --files-from copylist.txt wasabi:duplitech-samsung/poc/ s3:wasabi-to-s3-automated-data-transfer-logs/wasabi-files/  -vv --log-file=logfile.log
-      - echo "Migration completed successfully."
-      - echo Uploading log file to S3...
-      - aws s3 cp logfile.log s3://wasabi-to-s3-automated-data-transfer-logs/transfer-logs/
+      
+      - |
+        if rclone copy --files-from copylist.txt wasabi:duplitech-samsung/poc/ s3:wasabi-to-s3-automated-data-transfer-logs/wasabi-files/ --progress -vv --log-file $LOG_FILE; then
+          echo "Migration completed successfully."
+        else
+          echo "Migration failed." >&2
+          exit 1
+        fi
+      - echo "Uploading log file to S3..."
+      - aws s3 cp $LOG_FILE s3://wasabi-to-s3-automated-data-transfer-logs/transfer-logs/
 
 artifacts:
   files:
